import os
import subprocess

BLAST_BIN = r"B:\Stage\tools\blast\bin"

db_fasta = r"B:\Stage\DB_test\DB_FASTA_Test.fasta"
query_fasta = "query.fasta"


with open(query_fasta, "w") as f:
    f.write(
        ">OM250007.1 Lycopodium alpinum rbcL\n"
        "AAATGAGATATTTTATATAAATTTCTTACGAAACAGAGAATCCGTCTTAATGGACTTGACTATTCTTAGGAATAGACATCTCTTCATAGTAAAACATTATCATTGTATATTGTTTTTGATATGTGATGCAACCCAGTTGCTTTAATATCAGTAGAATTTTCATTTATGTTTCCCCCTAGGTTTTCTATATTGATATGAAACCTATTAAGTATCGAACTGATTGGTTAATGAAAAATGATTTTTACTGAACTAGTATTACATATTTCGATACGGGGGAAAGAAAAAAAAAACCCTAATTAATGTGATTTCAAATAAATAAATAAATAAATAAATAAATAAATAAATATATATATATTTATTTATTTATTTATTTATTTATTTTAATTTTGTGAGGAAAAGAAAAAAATTATTATCTTTTTCTTTTTCTAGTGGAAAGGAATCTTCCCACAATCCCGTATTGAGAATATGAGCCAAATATTAGGAATATGAGCTAAAATATAAATAAACTCAATATGAATAAGTAAATCAAGGTGGTAACTTTTATTCATAATCAACCGATCAACTCGGTATCAAAGATTGTTATCGATACAACCAAACAAATTTAATACTATTAGAATTTTATGGAAATAAATCCTTTTGCTCTTGGAGTTTCTACACTTGTCGACAGAAATGTAGGATATATCACTCAGA\n"
    )

# build a nucleotide BLAST database from the FASTA file
subprocess.run(
    [os.path.join(BLAST_BIN, "makeblastdb.exe"),
     "-in", db_fasta, "-dbtype", "nucl", "-out", "mydb"],
    check=True
)

# blastn query

result = subprocess.run(
    [os.path.join(BLAST_BIN, "blastn.exe"),
     "-query", query_fasta, "-db", "mydb", "-outfmt", "6"],
    capture_output=True, text=True, check=True
)

print(result.stdout)
