from gap_analysis import p_distance


seq1 = """TCGAAACCTGCCTAGCAGAACGACCCGCGAACCCGTTTCATCATCGGGGGGGAGCACGGG
TGCGAGAGCCTCGTGGTCCTCCTCCGCAGTCGGATCGACGGCGCTTGCGCCCTCTCTCCG
TCGGCACAATAACGAACCCCGGCGCGGACCGCGCCAAGGAAACTTAACAAGAGAGCGTGC
CCTTGCCTCCCCGGAAACGGTGTGTGCGCTTGTAGCATCGCCTTCTCTCACTATTTAAAA
CGACTCTCGGCAACGGATATCTCGGCTCTCGCATCGATGAAGAACGTAGCGAAATGCGAT
ACTTGGTGTGAATTGCAGAATCCCGTGAACCATCGAGTCTTTGAACGCAAGTTGCGCCCC
AAGCCGTTAGGCCGAGGGCACGCCTGCCTGGGTGTCACGCATCGTTGCCCCTCCCCCAAA
CCCCTCTCGACGAGGGGACTTGGCCGTGGGCGGATATTGGCCTCCCGTGCGCCGAAGGGC
TCGCGGTTGGCCTAAATACGAGTCGTCGACGGTGGACGTCGTGACGTTCGGTGGTCAAAC
AAACCTCGAGCTCCCGTCGCGCGTACGTCGTCGGTACAAACAAGGCTCACCGACCCTGAA
GCGTTGTCAACAACAGCGCACGCATCGCG"""

seq2 = """AACCTGCGGAAGGATCATTGTCGAAACCTGCCTAGCAGAACGACCCGCGAACCCGTTTCA
TCATCGGGGGGGAGCACGGGTGCGAGAGCCTCGTGGTCCCCCTCTGCAGTCGGATCGACG
GCGCCTGCGCCCTCGCTCCGTCGGCACAATAACGAACCCCGGCGCGGACCGCGCCAAGGA
AACTTAACAACAGAGCGTGCCCTTGCCTCCCCGGAAACGGTGTGTGCGCTTGTGGCATCG
CCTTCTCTCACTATTTAAAACGACTCTCGGCAACGGATATCTCGGCTCTCGCATCGATGA
AGAACGTAGCGAAATGCGATACTTGGTGTGAATTGCAGAATCCCGTGAACCATCGAGTCT
TTGAACGCAAGTTGCGCCCCAAGCCGTTAGGCCGAGGGCACGCCTGCCTGGGTGTCACGC
ATCGTTGCCCCTTCCCCGAACCCCCTCCCTTCCTTGAAAGAGGGAGACGAGGGGACTTCG
CCGTGGGCGGATATTGGCCTCCCGTGCGCCGAAGGGCTCGCGGTTGGCCTAAATACGAGT
CGTCGACGGTGGACGTCGTGACGTTCGGTGGTCAAACAAACCTCCAGCTCCCGTCGCGCG
TACGTCGTCGGTACAACAAGGCTCACCGACCCTGAAGCGTTGTCAACAGCGCACGCATC"""

if __name__ == "__main__":
    distance, n_sites = p_distance(seq1, seq2)
    print(f"seq1 vs seq2: distance={distance:.4f}, n_sites={n_sites}")

    identical_dist, identical_sites = p_distance(seq1, seq1)
    print(
        f"seq1 vs itself: distance={identical_dist}, n_sites={identical_sites}")

    one_diff_dist, one_diff_sites = p_distance("ACGTACGTAC", "ACGTACGTAG")
    print(
        f"1 diff / 10 sites: distance={one_diff_dist}, n_sites={one_diff_sites}")

    # one base deleted from the middle -> aligner should introduce a gap;
    # the gap column should be excluded, leaving distance 0 over 9 sites
    gap_dist, gap_sites = p_distance("ACGTACGTAC", "ACGTCGTAC")
    print(f"one deletion: distance={gap_dist}, n_sites={gap_sites}")
